version: '3.4'

services:
  identityserver:
    image: identityserver
    container_name: identityserver
    build:
      context: ./IdentityServer/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - VUE_APP_AUTH_SERVER_URL=http://localhost:5000
      - VUE_APP_CLIENT_URL=http://localhost:8080
      - VUE_APP_CLIENT_ID=vue.client


  vuefree:
    image: vuefree
    container_name: vuefree
    build:
      context: ./Vue/
      dockerfile: Dockerfile
    command: npm run serve
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - VUE_APP_AUTH_SERVER_URL=http://localhost:5000
      - VUE_APP_CLIENT_URL=http://localhost:8080
      - VUE_APP_CLIENT_ID=vue.client
      - VUE_APP_ALLOW_PROFILE_UPDATE=true
    depends_on:
      - identityserver
